name: Reusable CI/CD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

    secrets:
      PAT_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download env
        run: |
          curl -H "Authorization: token ${{secrets.PAT_TOKEN}}" -o .env.cicd https://raw.githubusercontent.com/lkduy2602/truyenthinh_configs/main/.env.cicd

      - name: Load env
        run: |
          cat .env.cicd >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Download Dockerfile
        run: |
          curl -H "Authorization: token ${{secrets.PAT_TOKEN}}" -o Dockerfile https://raw.githubusercontent.com/lkduy2602/truyenthinh_configs/main/backend/Dockerfile

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ format('{0}:{1}', github.repository, inputs.environment) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
